apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
spec:
  template:
    spec:
      containers:
        - name: server
          resources:
            requests:
              cpu: 150m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 128Mi