backend:
  type: es
  es:
    host: elasticsearch-master
rawConfig: |
  @INCLUDE fluent-bit-service.conf
  @INCLUDE fluent-bit-input.conf
  @INCLUDE fluent-bit-filter.conf
  @INCLUDE fluent-bit-output.conf
  [FILTER]
    Name modify
    Match *
    Remove time
    Remove @timestamp
  
  helm upgrade --install elasticsearch-exporter stable/elasticsearch-exporter --set  es.uri=http://elasticsearch-master:9200 --set serviceMonitor.enabled=true --namespace=observability