grafana:
  ingress:
    enabled: true

    # For Kubernetes >= 1.18 you should specify the ingress-controller via the field ingressClassName
    # See https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#specifying-the-class-of-an-ingress
    ingressClassName: nginx

    ## Hosts must be provided if Ingress is enabled.
    ##
    hosts:
     - grafana.alex.agx.ru

    ## Paths to use for ingress rules - one path should match the alertmanagerSpec.routePrefix
    ##
    path:   /
prometheus:
  prometheusSpec:
    tolerations:
      - key: node-role
        operator: Equal
        value: infra
        effect: NoSchedule