apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: web
spec:
  containers:
    - name: web
      image: alcaver/kub.hw1
      volumeMounts:
        - name: app
          mountPath: /app

  initContainers:
    - name: web-init
      image: busybox:stable
      command: [ 'sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh' ]
      volumeMounts:
      - name: app
        mountPath: /app
  volumes:
    - name: app
      emptyDir: { }
