apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
spec:
  template:
    spec:
      containers:
        - name: server
          env:
            - name: JAEGER_SERVICE_ADDR
              value: "jaeger-collector.observability.svc.cluster.local:14268"